const FETCH_COLLECTIONS_PENDING = "FETCH_COLLECTIONS_PENDING";
const FETCH_COLLECTIONS_SUCCESS = "FETCH_COLLECTIONS_SUCCESS";
const FETCH_COLLECTIONS_FAILED = "FETCH_COLLECTIONS_FAILED";

export default {
  FETCH_COLLECTIONS_SUCCESS,
  FETCH_COLLECTIONS_FAILED,
  FETCH_COLLECTIONS_PENDING,
};
