const FETCH_COLLECTION_ITEMS_PENDING = "FETCH_COLLECTION_ITEMS";
const FETCH_COLLECTION_ITEMS_SUCCESS = "FETCH_COLLECTION_ITEMS_SUCCESS";
const FETCH_COLLECTION_ITEMS_FAILED = "FETCH_COLLECTION_ITEMS_FAILED";

export default {
  FETCH_COLLECTION_ITEMS_PENDING,
  FETCH_COLLECTION_ITEMS_SUCCESS,
  FETCH_COLLECTION_ITEMS_FAILED,
};
