const FETCH_ALLITEMS_PENDING = "FETCH_ALLITEMS_PENDING";
const FETCH_ALLITEMS_SUCCESS = "FETCH_ALLITEMS_SUCCESS";
const FETCH_ALLITEMS_FAILED = "FETCH_ALLITEMS_FAILED";

export default {
  FETCH_ALLITEMS_SUCCESS,
  FETCH_ALLITEMS_PENDING,
  FETCH_ALLITEMS_FAILED,
};
